name: Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Run script
        run: python main/Solve_CW_4All.py

      - name: List all files in the current directory after running the script
        run: ls -Rla

      - name: Find all CSV files
        run: find . -name '*.csv'

      - name: Check if any CSV file exists
        run: |
          CSV_FILE=$(find . -name '*.csv')
          if [ -z "$CSV_FILE" ]; then
            echo "CSV file not found."
            exit 1
          else
            echo "CSV file(s) found:"
            echo "$CSV_FILE"
          fi
