name: Run Python Script

on: [push]

permissions: write-all

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Create necessary directories and set permissions
        run: |
          mkdir -p main/Results/Heuristic_Solutions
          chmod -R 777 main/Results/Heuristic_Solutions

      - name: Run script
        run: python main/Solve_CW_4All.py

      - name: Upload CSV as artifact if exists
        uses: actions/upload-artifact@v3
        with:
          name: csv-output
          path: main/Results/Heuristic_Solutions/*.csv