name: Start

on: [push]

permissions: write-all

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Create necessary directories and set permissions
        run: |
          mkdir -p main/Results/Heuristic_Solutions
          chmod -R 777 main/Results/Heuristic_Solutions

      - name: Run script Start
        run: python main/Start.py
